var DispatchConstants = {
  LOGIN_SUCCESS : "LOGIN_SUCCESS",
  LOGIN_FAILURE : "LOGIN_FAILURE",
  REGISTRATION_SUCCESS : "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE : "REGISTRATION_FAILURE",
  LOGGED_IN : "LOGGED_IN",
  LOGGED_OUT : "LOGGED_OUT",
  SAVE_SUCCESS : "SAVE_SUCCESS",
  SAVE_FAILURE : "SAVE_FAILURE",
  FETCH_SUCCESS : "FETCH_SUCCESS",
  FETCH_FAILURE : "FETCH_FAILURE",
  PICS_FETCH_SUCCESS : "PICS_FETCH_SUCCESS",
  PICS_FETCH_FAILURE : "PICS_FETCH_FAILURE"
};

module.exports = DispatchConstants;
